#! /bin/bash

E_ERROR=1

if [ -z "${IMAGE_NAME}" ]; then
	echo "Image is not built.  Run ./bin/build first"
	exit ${E_ERROR}
fi

IMAGE_NAME="statsy"
CONTAINER_NAME="${IMAGE_NAME}-container"

if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	rm -fr ./logs/*
fi

docker run -d \
	-v $(pwd)/logs:/var/log/supervisor \
	-p 80:80 \
	-p 2003:2003 \
	-p 2004:2004 \
	-p 9001:9001 \
	--name $CONTAINER_NAME \
	statsy
